#!/usr/bin/env bash
# self-check.sh — drift guard for the cost-estimate skill (the achievable form of P0-9).
#
# The report itself is produced by an LLM following skill/SKILL.md, so it cannot be
# byte-regenerated by a script. What CAN be guarded deterministically — and is, here:
#   A. every embedded ```bash block in SKILL.md parses (bash -n)         [embedding typos]
#   B. static audit: no nondeterminism / network / install / stale design  [discipline]
#   C. the Monte-Carlo kernel is byte-reproducible across runs            [determinism]
#   D. the structural-FP archetype gate stays N/A on the non-web fixture  [fairness regression]
#   E. the calibration fixture's source LOC still matches the shipped sample [sample drift]
#   F. both sample reports carry the current P2 framing                   [stale samples]
#
# Exit 0 = all pass; non-zero = at least one failure. Safe/read-only (uses a temp dir only).
# Usage:  bash scripts/self-check.sh   (run from the repo root or anywhere inside it)

set -u
ROOT=$(cd "$(dirname "$0")/.." && pwd)
SKILL="$ROOT/skill/SKILL.md"
CB="$ROOT/examples/calibration-codebase"
SELF_SAMPLE="$ROOT/examples/sample-report.md"
CB_SAMPLE="$ROOT/examples/sample-report-codebase.md"
FAILS=0
pass(){ printf '  \033[32mPASS\033[0m %s\n' "$1"; }
fail(){ printf '  \033[31mFAIL\033[0m %s\n' "$1"; FAILS=$((FAILS+1)); }
have(){ command -v "$1" >/dev/null 2>&1; }

echo "== cost-estimate self-check =="
[ -f "$SKILL" ] || { echo "SKILL.md not found at $SKILL"; exit 2; }
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT

# ---- A. every ```bash block parses ----
echo "A. SKILL.md bash blocks parse (bash -n)"
awk '/^```bash$/{f=1;n++;fn="'"$TMP"'/blk_"n".sh";next} /^```$/{f=0;next} f{print > fn}' "$SKILL"
nblk=$(ls "$TMP"/blk_*.sh 2>/dev/null | wc -l | tr -d ' '); aok=0; abad=0
for b in "$TMP"/blk_*.sh; do bash -n "$b" 2>"$TMP/err" && aok=$((aok+1)) || { abad=$((abad+1)); echo "    syntax error in block: $(cat "$TMP/err")"; }; done
[ "$abad" -eq 0 ] && pass "$nblk/$nblk blocks parse" || fail "$abad of $nblk blocks have syntax errors"

# ---- B. static audit ----
echo "B. static audit (nondeterminism / network / stale design)"
audit_bad=0
chk(){ # $1 = human label, $2 = grep -E pattern that must NOT appear
  if LC_ALL=C grep -nE "$2" "$SKILL" >/dev/null 2>&1; then fail "found forbidden: $1"; audit_bad=1; fi; }
chk "srand() with no seed"        'srand\(\)'
chk '$RANDOM'                      '\$RANDOM'
chk "time-based seeding"          'date \+%s|date \+%N'
chk "glibc LCG (overflows 2^53)"  '1103515245|2147483648'
chk "stale standalone Headline Valuation" '🏷️ Headline Valuation'
# network/install/test runners are allowed ONLY inside the Constraints prohibition lines ("Never ... ")
if LC_ALL=C grep -nE 'curl |wget |npm install|pip install|npm test|pytest |go test' "$SKILL" | grep -vE 'Never|Do not|do not|prohibit' >/dev/null 2>&1; then
  fail "network/install/test command outside the Constraints prohibition text"; audit_bad=1; fi
[ "$audit_bad" -eq 0 ] && pass "no forbidden patterns; one PRNG, no network/installs"

# ---- C. Monte-Carlo kernel determinism (reference re-implementation of Phase 3.9) ----
echo "C. Monte-Carlo band is byte-reproducible"
if have awk && [ "$(awk 'BEGIN{print (sqrt(4)==2)?1:0}' 2>/dev/null)" = 1 ]; then
  # gen(): emit the 10k sorted integer-dollar samples (reference re-impl of Phase 3.9, calibration toy)
  gen(){ awk -v C0=92500 -v GENF=0 -v CFC=29 -v TFC=34 -v CSUM=16 -v SP=0 'BEGIN{
      N=10000;M=2147483647;A=16807;Q=127773;R=2836; s=((CFC*1000003+TFC*10007+CSUM*101)%M); if(s<1)s=1
      sO=1-GENF-0.10; if(sO<0.05)sO=0.05; sM=1; sP=1.3; pM=1
      if(SP>0){sg=log(1.7);w=1.2816*sqrt(SP*SP+sg*sg);pO=exp(-w);pP=exp(w)}else{pO=0.5;pP=2}
      for(i=1;i<=N;i++){ms=tri(rng(),sO,sM,sP);mp=tri(rng(),pO,pM,pP);printf "%d\n",int(C0*ms*mp+0.5)}}
    function rng(  h,l){h=int(s/Q);l=s%Q;s=A*l-R*h;if(s<=0)s+=M;return s/M}
    function tri(u,O,Mo,P,  F){if(P<=O)return O;F=(Mo-O)/(P-O);if(u<F)return O+sqrt(u*(P-O)*(Mo-O));return P-sqrt((1-u)*(P-O)*(P-Mo))}' | LC_ALL=C sort -n; }
  hash(){ md5sum 2>/dev/null || md5; }
  h1=$(gen | hash); h2=$(gen | hash)
  if [ "$h1" = "$h2" ]; then
    pcts=$(gen | awk '{a[NR]=$1} END{ print rk(a,NR,0.10)" "rk(a,NR,0.50)" "rk(a,NR,0.90) }
      function rk(a,n,p,  i){i=int(p*n); if(i<p*n)i++; if(i<1)i=1; if(i>n)i=n; return a[i]}')
    set -- $pcts; p10=$1; p50=$2; p90=$3
    if [ "$p10" -le "$p50" ] && [ "$p50" -le "$p90" ] && [ "$p10" -ge 46250 ] && [ "$p90" -le 185000 ]; then
      pass "10k-sample band byte-identical across runs; monotone P10≤P50≤P90 in [0.5x,2.0x] (P10=$p10 P50=$p50 P90=$p90)"
    else fail "MC band invariant broken (P10=$p10 P50=$p50 P90=$p90)"; fi
  else fail "MC band differs across runs (nondeterministic)"; fi
else
  pass "skipped (awk math unavailable on this host — the skill's AWK_MATH=no fallback path applies)"
fi

# ---- D. archetype gate stays N/A on the non-web fixture ----
echo "D. structural-FP archetype gate is N/A on the parser/VM fixture"
if [ -d "$CB" ]; then
  INC="--include=*.py"; DEX="--exclude-dir=.git --exclude-dir=__pycache__"
  g(){ LC_ALL=C grep -rhoE $INC "$1" "$CB" $DEX 2>/dev/null | wc -l | tr -d ' '; }
  EI=$(g '@(app|router)\.(post|put|patch|delete)\b|@(Post|Put|Patch|Delete)Mapping\b')
  GET=$(g '@(app|router)\.get\b|@GetMapping\b')
  ILF=$(g 'class[[:space:]]+[A-Za-z_]+\((Base|db\.Model|models\.Model)\)|CREATE[[:space:]]+TABLE|@Entity\b')
  TX=$((EI+GET+ILF))
  [ "$TX" -eq 0 ] && pass "transaction_signal=0 on the calibration VM → IFPUG/COSMIC render N/A (no web-bias regression)" \
                   || fail "transaction_signal=$TX on the calibration VM (expected 0; anchored greps leaking)"
else
  pass "skipped (calibration fixture not present)"
fi

# ---- E. calibration fixture source LOC still matches the shipped sample ----
echo "E. calibration fixture LOC matches its sample report"
if [ -d "$CB" ] && have cloc; then
  loc=$(cloc --quiet --json "$CB" 2>/dev/null | (have jq && jq -r '.Python.code // 0' || grep -o '"code":[0-9]*' | head -1 | grep -o '[0-9]*'))
  want=$(grep -oE 'Effective KLOC\*\* \| [0-9.]+ KLOC|Total Lines of Code\*\* \| [0-9,]+' "$CB_SAMPLE" 2>/dev/null | grep -oE '2,?014|2\.01' | head -1)
  if [ -n "$loc" ] && [ "$loc" -ge 1990 ] && [ "$loc" -le 2040 ]; then
    pass "cloc Python code = $loc (sample states 2,014 / 2.01 KLOC; within tolerance)"
  else fail "cloc Python code = ${loc:-?}; sample states 2,014 — LOC drift, regenerate sample-report-codebase.md"; fi
else
  pass "skipped (no cloc or no fixture)"
fi

# ---- F. samples carry current P2 framing (not stale pre-P2 output) ----
echo "F. sample reports carry current P2 framing"
fbad=0
for f in "$SELF_SAMPLE" "$CB_SAMPLE"; do
  [ -f "$f" ] || { fail "missing sample: $f"; fbad=1; continue; }
  grep -q 'Headline: Reproduction-Cost Estimate' "$f" || { fail "$(basename "$f"): missing renamed headline section"; fbad=1; }
  grep -q 'Estimator Ensemble' "$f" || { fail "$(basename "$f"): missing Estimator Ensemble (stale pre-P2?)"; fbad=1; }
  grep -q '🏷️ Headline Valuation' "$f" && { fail "$(basename "$f"): has stale 'Headline Valuation' header"; fbad=1; }
done
[ "$fbad" -eq 0 ] && pass "both samples have the renamed headline + Estimator Ensemble, no stale headers"

echo
if [ "$FAILS" -eq 0 ]; then echo "ALL CHECKS PASSED ✅"; exit 0
else echo "$FAILS CHECK(S) FAILED ❌  — review above (a sample may need regenerating via the A17 temp-dir method)"; exit 1; fi
